// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Create a new project database at `project_path` and open it as the active project.
	 *  #
	 */
	createProject: (name: string, projectPath: string) => typedError<ProjectSummary, AppError>(__TAURI_INVOKE("create_project", { name, projectPath })),
	/**
	 *  Open an existing project file as the active project.
	 * 
	 *  Pass `password` when the database is encrypted. This also covers the unlock flow:
	 *  if a previous `open_project` returned a lock error, call again with the password.
	 */
	openProject: (projectPath: string, password: string | null) => typedError<ProjectSummary, AppError>(__TAURI_INVOKE("open_project", { projectPath, password })),
	/**
	 *  Close the active project and release its database connection.
	 *  #
	 */
	closeProject: () => typedError<null, AppError>(__TAURI_INVOKE("close_project")),
	/**
	 *  Load the full settings snapshot (project + global settings + all plugin configs).
	 *  #
	 */
	loadSettings: () => typedError<ProjectSettingsPayload, AppError>(__TAURI_INVOKE("load_settings")),
	/**
	 *  Update the project-wide theme setting.
	 *  #
	 */
	updateProjectSettings: (name: string | null, theme: string | null) => typedError<ProjectSettingsRecord, AppError>(__TAURI_INVOKE("update_project_settings", { name, theme })),
	/**
	 *  Set one plugin setting value within the active project.
	 *  #
	 */
	setPluginSetting: (pluginId: string, settingName: string, value: SettingValue) => typedError<PluginRecord, AppError>(__TAURI_INVOKE("set_plugin_setting", { pluginId, settingName, value })),
	/**
	 *  Register or refresh a plugin from a directory on disk into the active project.
	 *  #
	 */
	upsertProjectPluginFromDir: (pluginDir: string) => typedError<PluginRecord, AppError>(__TAURI_INVOKE("upsert_project_plugin_from_dir", { pluginDir })),
	/**
	 *  Register or refresh a plugin from a `.zip` archive into the active project.
	 *  #
	 */
	upsertProjectPluginFromZip: (zipPath: string) => typedError<PluginRecord, AppError>(__TAURI_INVOKE("upsert_project_plugin_from_zip", { zipPath })),
	/**
	 *  Create a new scan in Draft status.
	 *  #
	 */
	createScan: (preview: string | null) => typedError<ScanSummaryRecord, AppError>(__TAURI_INVOKE("create_scan", { preview })),
	/**
	 *  List all scans for the active project including archived ones.
	 *  #
	 */
	listScans: () => typedError<ScanSummaryRecord[], AppError>(__TAURI_INVOKE("list_scans")),
	/**
	 *  Fetch full details of a single scan including all plugin results.
	 *  #
	 */
	getScan: (scanId: string) => typedError<ScanDetailRecord, AppError>(__TAURI_INVOKE("get_scan", { scanId })),
	/**
	 *  Execute a scan: run the selected plugins and persist results.
	 * 
	 *  Plugin code is read from the project database, not from disk.
	 */
	runScan: (scanId: string, selectedPlugins: PluginEntrypointSelection[], inputs: ScanEntrypointInput[]) => typedError<ScanSummaryRecord, AppError>(__TAURI_INVOKE("run_scan", { scanId, selectedPlugins, inputs })),
	/**
	 *  Update the preview (display name) of a scan.
	 *  #
	 */
	updateScanPreview: (scanId: string, preview: string) => typedError<ScanSummaryRecord, AppError>(__TAURI_INVOKE("update_scan_preview", { scanId, preview })),
	// Mark a scan as archived or active without deleting it from the database.
	setScanArchived: (scanId: string, archived: boolean) => typedError<ScanSummaryRecord, AppError>(__TAURI_INVOKE("set_scan_archived", { scanId, archived })),
	// Persist the explicit UI ordering for all scans in the active project.
	reorderScans: (orderedScanIds: string[]) => typedError<ScanSummaryRecord[], AppError>(__TAURI_INVOKE("reorder_scans", { orderedScanIds })),
	/**
	 *  Probe the lock status of a project file *without* opening it.
	 * 
	 *  Call this before `open_project` to determine whether a password prompt is needed.
	 */
	getProjectLockStatus: (projectPath: string) => typedError<ProjectLockStatus, string>(__TAURI_INVOKE("get_project_lock_status", { projectPath })),
	/**
	 *  Encrypt an unencrypted project database with `new_password`.
	 *  #
	 */
	setProjectPassword: (newPassword: string) => typedError<ProjectLockStatus, string>(__TAURI_INVOKE("set_project_password", { newPassword })),
	/**
	 *  Re-encrypt the database, replacing the current password with `new_password`.
	 *  #
	 */
	changeProjectPassword: (currentPassword: string, newPassword: string) => typedError<ProjectLockStatus, string>(__TAURI_INVOKE("change_project_password", { currentPassword, newPassword })),
	/**
	 *  Remove encryption from the project database.
	 *  #
	 */
	removeProjectPassword: (currentPassword: string) => typedError<ProjectLockStatus, string>(__TAURI_INVOKE("remove_project_password", { currentPassword })),
};

/* Types */
// Typed error returned by all Tauri commands.
export type AppError = { kind: "validation"; message: string } | { kind: "notFound"; message: string } | { kind: "database"; message: string } | { kind: "internal"; message: string };

// A single console log entry captured from plugin execution.
export type LogEntry = {
	level: LogLevel,
	message: string,
};

// Log severity level emitted by a plugin during execution.
export type LogLevel = "log" | "warn" | "error";

// Author entry from a plugin manifest.
export type PluginAuthor = {
	name: string,
	email: string | null,
};

// Named entrypoint exposed by a plugin.
export type PluginEntrypointRecord = {
	id: string,
	name: string,
	functionName: string,
	description: string | null,
};

// One selected `(plugin, entrypoint)` pair submitted when running a scan.
export type PluginEntrypointSelection = {
	pluginId: string,
	entrypointId: string,
};

// Structured input/setting type descriptor.
export type PluginFieldTypeDef = {
	name: string,
	values: string[] | null,
};

// Definition of one input field declared by a plugin.
export type PluginInputDef = {
	entrypointId: string,
	name: string,
	title: string,
	type: PluginFieldTypeDef,
	optional: boolean,
	description: string | null,
	defaultValue: SettingValue | null,
};

// Core manifest metadata for a plugin.
export type PluginManifestRecord = {
	id: string,
	name: string,
	version: string,
	description: string,
	license: string,
	authors: PluginAuthor[],
	icon: string | null,
	homepage: string | null,
};

// Structured result of executing one plugin entrypoint.
export type PluginOutput = {
	// Whether the plugin executed successfully.
	ok: boolean,
	// JSON-encoded output data (present when `ok` is true).
	dataJson: string | null,
	// Error message (present when `ok` is false).
	error: string | null,
	// Console log entries captured during execution.
	logs: LogEntry[],
};

// Complete descriptor for a plugin as configured within a project.
export type PluginRecord = {
	id: string,
	name: string,
	version: string,
	manifest: PluginManifestRecord,
	entrypoints: PluginEntrypointRecord[],
	inputDefs: PluginInputDef[],
	settingDefs: PluginSettingDef[],
	settingValues: PluginSettingValue[],
};

// Definition of one configurable setting declared by a plugin.
export type PluginSettingDef = {
	name: string,
	title: string,
	type: PluginFieldTypeDef,
	description: string | null,
	required: boolean,
	defaultValue: SettingValue | null,
};

// A named setting value with its typed scalar.
export type PluginSettingValue = {
	name: string,
	value: SettingValue,
};

// Encryption and unlock state of a project database file.
export type ProjectLockStatus = {
	locked: boolean,
	unlocked: boolean,
};

// Full project settings snapshot: project info, global settings, and all plugin configs.
export type ProjectSettingsPayload = {
	project: ProjectSummary,
	projectSettings: ProjectSettingsRecord,
	plugins: PluginRecord[],
};

// Project-wide settings record persisted in the `ProjectSettings` table.
export type ProjectSettingsRecord = {
	id: string,
	description: string,
	locale: string,
	theme: string,
};

// Lightweight project summary returned after open/create.
export type ProjectSummary = {
	id: string,
	name: string,
	audit: string | null,
	directory: string,
};

// Full scan details: metadata, selected plugins, inputs, and all plugin results.
export type ScanDetailRecord = {
	id: string,
	status: string,
	preview: string | null,
	selectedPlugins: PluginEntrypointSelection[],
	inputs: ScanEntrypointInput[],
	results: ScanPluginResultRecord[],
};

// A single field value submitted as input to one plugin entrypoint.
export type ScanEntrypointInput = {
	pluginId: string,
	entrypointId: string,
	fieldName: string,
	value: SettingValue,
};

// Single plugin result stored in a completed scan.
export type ScanPluginResultRecord = {
	pluginId: string,
	entrypointId: string,
	output: PluginOutput,
};

// Brief scan record used in list views and status responses.
export type ScanSummaryRecord = {
	id: string,
	status: string,
	preview: string | null,
	isArchived: boolean,
	sortOrder: number,
};

// A typed scalar value used for both plugin settings and scan inputs.
export type SettingValue = { type: "string"; value: string } | { type: "number"; value: number } | { type: "boolean"; value: boolean } | { type: "null" };

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

