// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InstalledPlugin = { plugin: Plugin, enabled: boolean, settings: PluginSettings, installation_path: string, };

export type Plugin = { id: PluginId, name: string, version: string, description: string, authors: Array<string>, license: string, entrypoint: string, default_settings: PluginSettings, inputs: PluginInputs, };

export type PluginId = string;

export type PluginInput = { name: string, optional: boolean, input_type: PluginInputType, description: string, };

export type PluginInputType = { "string": string | null } | { "number": bigint | null } | { "switch": Array<PluginSwitchOption> } | { "toggle": boolean | null };

export type PluginInputs = Array<PluginInput>;

export type PluginSetting = { name: string, value: PluginSettingValue, description: string, };

export type PluginSettingValue = { "string": string } | { "number": bigint } | { "float": number } | { "toggle": boolean };

export type PluginSettings = Array<PluginSetting>;

export type PluginSwitchOption = { name: string, extra_inputs: Array<PluginInput>, };
