// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginId, PluginSettings } from "./Plugin";

export type Project = { id: ProjectId, name: string, settings: ProjectSettings, plugin_settings: Array<ProjectPluginSettings>, };

export type ProjectId = string;

export type ProjectPluginSettings = { id: PluginId, settings: PluginSettings, };

export type ProjectSettings = { description: string, locale: string, };
