// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectPluginSettings } from "./ProjectPluginSettings";
import type { ProjectSettings } from "./ProjectSettings";

export type Project = { id: string, name: string, settings: ProjectSettings, plugin_settings: Array<ProjectPluginSettings>, };
