// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { Node } from "./Node";

export type TypeValue = { "String": string } | { "Number": bigint } | { "Address": Address } | { "TableData": [Array<string>, Array<Node>] };
