// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReactTypeHint } from "./ReactTypeHint";
import type { TypeValue } from "./TypeValue";

export type Type = { _type: ReactTypeHint, value: TypeValue, };
