export const REGISTRY_JURISDICTION_LABELS = {
    "ae_az": "United Arab Emirates - Abu Dhabi",
    "ae_du": "United Arab Emirates - Dubai",
    al: "Albania",
    au: "Australia",
    aw: "Aruba",
    bb: "Barbados",
    bd: "Bangladesh",
    be: "Belgium",
    bg: "Bulgaria",
    bh: "Bahrain",
    bl: "Saint Barthelemy",
    bm: "Bermuda",
    bo: "Bolivia",
    br: "Brazil",
    bs: "Bahamas",
    by: "Belarus",
    bz: "Belize",
    ca: "Canada",
    "ca_bc": "Canada - British Columbia",
    "ca_nb": "Canada - New Brunswick",
    "ca_nl": "Canada - Newfoundland and Labrador",
    "ca_ns": "Canada - Nova Scotia",
    "ca_nu": "Canada - Nunavut",
    "ca_on": "Canada - Ontario",
    "ca_pe": "Canada - Prince Edward Island",
    "ca_qc": "Canada - Quebec",
    ch: "Switzerland",
    cw: "Curacao",
    cy: "Cyprus",
    cz: "Czech Republic",
    de: "Germany",
    dk: "Denmark",
    "do": "Dominican Republic",
    es: "Spain",
    fi: "Finland",
    fr: "France",
    gb: "United Kingdom",
    gf: "French Guiana",
    gg: "Guernsey",
    gi: "Gibraltar",
    gl: "Greenland",
    gp: "Guadeloupe",
    gr: "Greece",
    hk: "Hong Kong",
    hr: "Croatia",
    ie: "Ireland",
    il: "Israel",
    im: "Isle of Man",
    "in": "India",
    ir: "Iran",
    is: "Iceland",
    je: "Jersey",
    jm: "Jamaica",
    jp: "Japan",
    kh: "Cambodia",
    li: "Liechtenstein",
    lu: "Luxembourg",
    lv: "Latvia",
    md: "Moldova",
    me: "Montenegro",
    mf: "Saint Martin (French part)",
    mm: "Myanmar",
    mq: "Martinique",
    mt: "Malta",
    mu: "Mauritius",
    mx: "Mexico",
    my: "Malaysia",
    nc: "New Caledonia",
    nl: "Netherlands",
    no: "Norway",
    nz: "New Zealand",
    pa: "Panama",
    pf: "French Polynesia",
    pk: "Pakistan",
    pl: "Poland",
    pm: "Saint Pierre and Miquelon",
    pr: "Puerto Rico",
    re: "Reunion",
    ro: "Romania",
    rw: "Rwanda",
    se: "Sweden",
    sg: "Singapore",
    si: "Slovenia",
    sk: "Slovakia",
    th: "Thailand",
    tj: "Tajikistan",
    tn: "Tunisia",
    to: "Tonga",
    tz: "Tanzania",
    ua: "Ukraine",
    ug: "Uganda",
    "us_ak": "United States - Alaska",
    "us_al": "United States - Alabama",
    "us_ar": "United States - Arkansas",
    "us_az": "United States - Arizona",
    "us_ca": "United States - California",
    "us_co": "United States - Colorado",
    "us_ct": "United States - Connecticut",
    "us_dc": "United States - District of Columbia",
    "us_de": "United States - Delaware",
    "us_fl": "United States - Florida",
    "us_ga": "United States - Georgia",
    "us_hi": "United States - Hawaii",
    "us_ia": "United States - Iowa",
    "us_id": "United States - Idaho",
    "us_il": "United States - Illinois",
    "us_in": "United States - Indiana",
    "us_ks": "United States - Kansas",
    "us_ky": "United States - Kentucky",
    "us_la": "United States - Louisiana",
    "us_ma": "United States - Massachusetts",
    "us_md": "United States - Maryland",
    "us_me": "United States - Maine",
    "us_mi": "United States - Michigan",
    "us_mn": "United States - Minnesota",
    "us_mo": "United States - Missouri",
    "us_ms": "United States - Mississippi",
    "us_mt": "United States - Montana",
    "us_nc": "United States - North Carolina",
    "us_nd": "United States - North Dakota",
    "us_ne": "United States - Nebraska",
    "us_nh": "United States - New Hampshire",
    "us_nj": "United States - New Jersey",
    "us_nm": "United States - New Mexico",
    "us_nv": "United States - Nevada",
    "us_ny": "United States - New York",
    "us_oh": "United States - Ohio",
    "us_ok": "United States - Oklahoma",
    "us_or": "United States - Oregon",
    "us_pa": "United States - Pennsylvania",
    "us_ri": "United States - Rhode Island",
    "us_sc": "United States - South Carolina",
    "us_sd": "United States - South Dakota",
    "us_tn": "United States - Tennessee",
    "us_tx": "United States - Texas",
    "us_ut": "United States - Utah",
    "us_va": "United States - Virginia",
    "us_vt": "United States - Vermont",
    "us_wa": "United States - Washington",
    "us_wi": "United States - Wisconsin",
    "us_wv": "United States - West Virginia",
    "us_wy": "United States - Wyoming",
    vn: "Vietnam",
    vu: "Vanuatu",
    wf: "Wallis and Futuna",
    yt: "Mayotte",
    za: "South Africa",
} as const;

export type RegistryJurisdictionCode = keyof typeof REGISTRY_JURISDICTION_LABELS;

export const REGISTRY_JURISDICTION_CODES = Object.keys(
    REGISTRY_JURISDICTION_LABELS,
) as RegistryJurisdictionCode[];

export const REGISTRY_JURISDICTION_OPTIONS = REGISTRY_JURISDICTION_CODES
    .map((value) => ({
        value,
        label: REGISTRY_JURISDICTION_LABELS[value],
    }))
    .sort((a, b) => a.label.localeCompare(b.label));

export function isRegistryJurisdictionCode(value: string): value is RegistryJurisdictionCode {
    return Object.prototype.hasOwnProperty.call(REGISTRY_JURISDICTION_LABELS, value);
}

export function getRegistryJurisdictionLabel(value: string): string {
    if (isRegistryJurisdictionCode(value)) {
        return REGISTRY_JURISDICTION_LABELS[value];
    }

    return value;
}

export function formatRegistryJurisdictionValue(value: string): string {
    const label = getRegistryJurisdictionLabel(value);
    return label === value ? value : `${label} (${value})`;
}
